// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnulmlqabygnyykjgndk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudWxtbHFhYnlnbnl5a2pnbmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDUzMTIsImV4cCI6MjA2MDM4MTMxMn0.8y_adjTRXPiMiKO9SjzVO2QdPga6IxnvEY7kN6TqJwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);